Yan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

handler404 = 'store.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),

    # Social Auth
    path('auth/', include('social_django.urls', namespace='social')),    # path('accounts/', include('allauth.urls')),

    path('login/', views.perform_login, name='login'),
    path('logout/', views.perform_logout, name='logout'),
    # path('social-auth/', include('social_django.urls', namespace='social')),
    path('home', TemplateView.as_view(template_name='dashboard/home.html'), name='home'),

    # Custom Apps
    path('', include('accounts.urls')),
    path('', include('store.urls')),
    path('', include('cust_admin.urls')),
    path('', include('cust_auth_admin.urls')),
    path('', include('user_cart.urls')),

    # Password Reset
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='account/pass_reset_form.html'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='account/pass_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/pass_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/pass_reset_complete.html'), name='password_reset_complete'),

    # Home
    # path('home/', TemplateView.as_view(template_name='dashboard/home.html'), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cust_admin/urls.py
from django.urls import path
from cust_admin import views

app_name = 'cust_admin'

urlpatterns = [
    path('admin_dashboard/', views.dashboard, name='admin_dashboard'),

    # User functoinalities
    path('user_view/<str:username>/', views.user_view, name='user_view'),
    path('user_list/', views.user_list, name='user_list'),
    path('user_block/<str:username>/', views.user_block_unblock, name='user_block'),

    # Product functionalities 
    path('add_product/', views.add_product, name='add_product'),
    path('prod_list/', views.prod_list, name='prod_list'),
    # path('product_unlist/<int:product_id>/', views.product_list_unlist, name='product_unlist'),
    path('product_unlist/<int:product_id>/', views.product_list_unlist, name='product_unlist'),
    # path('product_edit/<int:p_id>', views.prod_edit, name='product_edit'),
    path('product_edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('prod_variant_assign/', views.prod_variant_assign, name='prod_variant_assign'),
    path('prod_variant_edit/<int:pk>/', views.prod_variant_edit, name='prod_variant_edit'),
    path('prod_catalogue/', views.prod_catalogue_list, name='prod_catalogue'),
    path('catalogue_unlist/<int:pk>/', views.catalogue_list_unlist, name='catalogue_unlist'),
    
    # Category functionalities
    path('category_list', views.category_list, name='category_list'),
    path('add_category/', views.add_category, name='add_category'),
    path('category_unlist/<int:c_id>/', views.category_list_unlist, name='category_unlist'),
    path('category_edit/<int:c_id>', views.edit_category, name='category_edit'),

    # subcategory functionalities
    # path('add_subcat/', views.add_subcat, name='add_subcat'),
    # path('subcategory_list/', views.subcategory_list, name='subcategory_list'),

    # Variant functionalities
    path('add_variant', views.add_variant, name='add_variant'),
    path('list_variant/', views.list_variant, name='list_variant'),
    path('edit_variant/<int:id>/', views.edit_variant, name='edit_variant'),

    # Order functionalities
    path('orders/', views.list_order, name='list_order'),
    path('orders/<int:order_id>/', views.order_detail, name='order_detail'),
    # path('orders/<int:order_id>/update_status/', views.order_update_status, name='order_update_status'),
    path('order/update_status/<int:order_id>/', views.order_update_status, name='order_update_status'),
    path('returned_orders/return-requests/', views.manage_return_requests, name='returned_orders'),

    # coupon functionalities
    path('add-coupon/', views.add_coupon, name='add_coupon'),
    path('coupons/', views.coupon_list, name='coupon_list'),
    path('edit-coupon/<int:coupon_id>/', views.edit_coupon, name='edit_coupon'),
    path('delete-coupon/<int:coupon_id>/', views.delete_coupon, name='delete_coupon'),
    # category offer functionalities
    path('category_offer/', views.category_offer_list, name='category_offer_list'),
    path('category_offer/add/', views.add_category_offer, name='add_category_offer'),
    path('category_offer/edit/<int:offer_id>/', views.edit_category_offer, name='edit_category_offer'),
    path('category_offer/delete/<int:offer_id>/', views.delete_category_offer, name='delete_category_offer'),
    # product offer functionalities
    path('product_offer/', views.product_offer_list, name='product_offer_list'),
    path('product_offer/add/', views.add_product_offer, name='add_product_offer'),
    path('product_offer/edit/<int:offer_id>/', views.edit_product_offer, name='edit_product_offer'),
    path('product_offer/delete/<int:offer_id>/', views.delete_product_offer, name='delete_product_offer'),
    # sales statistics
    path('sales-report/', views.sales_report, name='sales_report'),
    path('daily-report/', views.daily_report, name='daily_report'),
    path('weekly-report/', views.weekly_report, name='weekly_report'),
    path('monthly-report/', views.monthly_report, name='monthly_report'),
    # pdf / excel export
    path('export-pdf/<str:report_type>/', views.export_to_pdf, name='export_pdf'),
    path('export-excel/<str:report_type>/', views.export_to_excel, name='export_excel'),
    # graph statistics
    path('get_daily_sales_data/', views.get_daily_sales_data, name='get_daily_sales_data'),
    path('get_monthly_sales_data/', views.get_monthly_sales_data, name='get_monthly_sales_data'),
    path('get_yearly_sales_data/', views.get_yearly_sales_data, name='get_yearly_sales_data'),
    path('get_order_status_data/', views.get_order_status_data, name='get_order_status_data'),
    path('sales_statistics/', views.sales_statistics, name='sales_statistics'),
    path('export-custom-sales-report/', views.sales_report, name='export_custom_sales_report'),
    # Best selling 
    path('best-selling-products/', views.best_selling_products, name='best_selling_products'),
    # path('best-selling-subcategories/', views.best_selling_subcategories, name='best_selling_subcategories'),
    # path('best-selling-brands/', views.best_selling_brands, name='best_selling_brands'),
]

cust_admin/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from accounts.models import User
from cust_auth_admin.views import admin_required
from store.models import *
from django.http import HttpResponseBadRequest, HttpResponse, JsonResponse
from cust_admin.forms import ProductVariantAssignForm, CouponForm, CategoryOfferForm, ProductOfferForm
from django.contrib import messages
from decimal import Decimal
import sweetify
from collections import defaultdict
from django.contrib.auth.decorators import login_required
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.db import IntegrityError
from PIL import Image
from django.db.models import Case, CharField, Value, When, Count, Sum
from django.utils import timezone
from datetime import datetime, timedelta
from django.template.loader import get_template
from xhtml2pdf import pisa
import pandas as pd
from django.urls import reverse
from .utils import paginate_queryset
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.cache import never_cache
from django.utils.timezone import localdate, make_aware
from django.views.decorators.http import require_POST
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt


#=========================================== admin dashboard ===========================================================================================================================


@admin_required
@never_cache
def dashboard(request):
    product_count = Product.objects.count()
    cat_count = Category.objects.count()
    usr_count = User.objects.count()
    order_count = CartOrder.objects.count()

    # Calculate total revenue from delivered orders
    delivered_orders = CartOrder.objects.filter(status='Delivered')
    total_revenue = delivered_orders.aggregate(total=Sum('order_total'))['total'] or 0

    # Paginate the orders
    orders_list = CartOrder.objects.all().order_by('-id')
    paginator = Paginator(orders_list, 10)  # Show 10 orders per page

    page = request.GET.get('page')
    try:
        orders = paginator.page(page)
    except PageNotAnInteger:
        orders = paginator.page(1)
    except EmptyPage:
        orders = paginator.page(paginator.num_pages)

    context = {
        'title': 'Admin Dashboard',
        'usr_count': usr_count,
        'order_count': order_count,
        'orders': orders_list,
        'product_count': product_count,
        'cat_count': cat_count,
        'total_revenue': total_revenue,
    }
    return render(request, 'cust_admin/index.html', context)


#=========================================== admin list, view, delete user =========================================================================================================


@admin_required
def user_list(request):
    users = User.objects.all().order_by('id')
    page_obj, paginator = paginate_queryset(request, users, items_per_page=20)  # Adjust items_per_page as needed

    context={
        'title':'User List',
         'users': users,
         'page_obj': page_obj,
         'paginator': paginator
         }
    return render(request, 'cust_admin/user/user_list.html', context)


@admin_required
def user_view(request, username):
    user = get_object_or_404(User, username=username)
    context = {
        'title': 'View User',
        'user': user
        }
    return render(request, 'cust_admin/user/user_view.html', context)

User = get_user_model()


@admin_required
def user_block_unblock(request, username):
    user = get_object_or_404(User, username = username)
    user.is_active = not user.is_active
    user.save()
    action = 'blocked' if not user.is_active else 'unblocked'
    sweetify.toast(request, f"The user {user.username} has been {action} successfully.", icon='success', timer=3000)
    return redirect('cust_admin:user_list')


#=========================================== admin add, list, edit, delete category=========================================================================================================


@admin_required
def category_list(request):
    categories = Category.objects.all().order_by('c_id')
    page_obj, paginator = paginate_queryset(request, categories, items_per_page=20)  # Adjust items_per_page as needed

    context = {
        'title':'Category List',
        'categories':categories,
        'page_obj': page_obj,
        'paginator': paginator,

        }
    return render(request, 'cust_admin/category/category_list.html', context)


@admin_required
def add_category(request):
    context = {
        'title': 'Add Category'
    }

    if request.method == 'POST':
        c_name = request.POST.get('cname')
        c_image = request.FILES.get('image')

        # Check if a category with the same name already exists
        existing_category = Category.objects.filter(c_name=c_name).exists()
        if existing_category:
            sweetify.toast(request, f"Category {c_name} with this name already exists.", icon='error', timer=3000)
        else:
            # Create and save the new category
            c_data = Category(c_name=c_name, c_image=c_image)
            c_data.save()
            sweetify.toast(request, "Category added successfully.", icon='success', timer=3000)
            return redirect('cust_admin:category_list')

    return render(request, 'cust_admin/category/add_category.html', context)


@admin_required
def category_list_unlist(request, c_id):
    category = get_object_or_404(Category, c_id = c_id)
    category.is_blocked = not category.is_blocked    
    category.save()
    action = 'unblocked' if not category.is_blocked else 'blocked'
    sweetify.toast(request, f"The category with ID {category.c_id} has been {action} successfully.", icon='success', timer=3000)
    return redirect('cust_admin:category_list')


@admin_required
def edit_category(request, c_id):
    category = get_object_or_404(Category, c_id=c_id)
    
    if request.method == 'POST':
        category.c_name = request.POST.get('cname')
        if request.FILES.get('image'):  # Only update the image if a new one is uploaded
            category.c_image = request.FILES.get('image')
        # Save the updated category
        category.save()
        return redirect('cust_admin:category_list')

    # Pass the category data to the template to prefill the form
    context = {
        'title': 'Edit Category',
        'category': category,
    }
          
    return render(request, 'cust_admin/category/category_edit.html', context)



#=========================================== admin add, list subcategory =========================================================================================================


# @admin_required
# def subcategory_list(request):
#     sub_cat = Subcategory.objects.all()
#     context = {
#         'title':'Sub Category',
#         'sub_cat':sub_cat,
#                }
#     return render(request,'cust_admin/sub_category/sub_cat_list.html', context)


# @admin_required
# def add_subcat(request):
#     if request.method == 'POST':
#         sub_name = request.POST.get('sub_name')
#         # c_id = request.POST.get('category')
#         # category = Category.objects.get(c_id = c_id)
#         Subcategory.objects.create(sub_name = sub_name)
#         return redirect('cust_admin:subcategory_list')
#     # categories = Category.objects.all()
#     return render(request, 'cust_admin/sub_category/add_sub_cat.html', {'title':'Add Sub Category'})


#=========================================== admin add, list, edit, delete variant =========================================================================================================


@admin_required
def list_variant(request):
    # Define the custom ordering based on the size values
    custom_ordering = Case(
        When(size='S', then=Value(0)),
        When(size='M', then=Value(1)),
        When(size='L', then=Value(2)),
        When(size='XL', then=Value(3)),
        When(size='XXL', then=Value(4)),
        When(size='XXXL', then=Value(5)),
        default=Value(5),
        output_field=CharField(),
    )

    # Fetch the Size objects ordered according to the custom ordering
    data = Size.objects.all().order_by(custom_ordering)

    context = {
        'data': data,
        'title': 'Variant List',
    }
    return render(request, 'cust_admin/variant/variant_list.html', context)


@admin_required
def add_variant(request):
    if request.method == 'POST':
        size = request.POST.get('size')

        try:
            existing_size = Size.objects.filter(size__iexact=size)
            if existing_size:
                sweetify.toast(request, "The size already exists", timer=3000, icon='warning')
            else:
                new_size = Size(size=size)
                new_size.save()
                sweetify.toast(request, f'The size {size} added successfully', icon='success', timer=3000)
        except IntegrityError as e:
            error_message = str(e)
            sweetify.toast(request, f'An error occurred while adding the size: {error_message}', icon='alert', timer=3000)
        
        return redirect('cust_admin:list_variant')
    context = {
            'title': 'Variant Add',
        }
    return render(request, 'cust_admin/variant/variant_add.html', context)


@admin_required
def edit_variant(request, id):
    if request.method == 'POST':
        size = request.POST.get('size')
        price_increment = request.POST.get('price_inc')
        edit=Size.objects.get(id=id)
        edit.size = size
        edit.price_increment = price_increment
        edit.save()
        return redirect('cust_admin:list_variant')
    obj = Size.objects.get(id=id)
    context = {
        "obj":obj,
        'title': 'Variant Edit',
    }
    
    return render(request, 'cust_admin/variant/variant_edit.html', context)

templates/cust_admin/product/prod_variant_assign.html
{% extends 'cust_admin/base.html' %}
{% load static %}
{% block content %}
<section class="content-main">
    <div class="row">
        <div class="col-9">
            <div class="content-header">
                <h2 class="content-title">{{ title }}</h2>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="card mb-4">
                <div class="card-header">
                    <h4>Basic</h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-md rounded font-sm hover-up">Add Product</button> &nbsp;
                        <a href="{% url 'cust_admin:prod_list' %}" class="btn btn-light rounded font-sm mr-5 text-body hover-up">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/cust_admin/product/product_catalogue.html
{% extends 'cust_admin/base.html' %}
{% load static %}
{% block content %}
    
    
        <section class="content-main">
            <div class="content-header">
                <div>
                    <h2 class="content-title card-title">{{ title }}</h2>
                    <p></p>
                </div>
                <div>
                    <a href="{% url 'cust_admin:prod_variant_assign' %}" class="btn btn-md rounded font-sm">Add New Product</a>
                </div>
            </div>
            <div class="card mb-4">
                <header class="card-header">
                    <div class="row gx-3">
                        <div class="col-lg-4 col-md-6 me-auto">
                            <input type="text" placeholder="Search..." class="form-control">
                        </div>
                        <div class="col-lg-2 col-6 col-md-3">
                            <select class="form-select">
                                <option>Status</option>
                                <option>Active</option>
                                <option>Blockd</option>
                                <option>Show all</option>
                            </select>
                        </div>
                        <div class="col-lg-2 col-6 col-md-3">
                            <select class="form-select">
                                <option>Show 20</option>
                                <option>Show 30</option>
                                <option>Show 40</option>
                            </select>
                        </div>
                    </div>
                </header> <!-- card-header end// -->
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Image</th>
                                    <th scope="col">Size</th>
                                    <th scope="col">Category</th>
                                    {% comment %} <th scope="col">Sub Category</th> {% endcomment %}
                                    <th scope="col">Price</th>
                                    <th>Stock</th> 
                                    <th scope="col" class="text-end">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for product_attr in products %}
                                <tr>
                                    <td>{{ product_attr.id }}</td>
                                    <td><b>{{ product_attr.product.title }}</b></td>
                                    <td>
                                        {% if product_attr.product.image %}
                                        <img src="{{ product_attr.product.image.url }}" alt="{{ product_attr.product.title }}" class="img-sm img-thumbnail" alt="">
                                        {% else %}
                                        <p>No image available</p>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if product_attr.size %}
                                        <p>{{ product_attr.size.size }}</p>
                                        {% else %}
                                        <p>No size available</p>
                                        {% endif %}
                                    </td>
                                    <td>{{ product_attr.product.category }}</td>
                                    {% comment %} <td>{{ product_attr.product.sub_category.sub_name }}</td> {% endcomment %}
                                    <td>{{product_attr.price}}</td>
                                    <td>{{ product_attr.stock }}</td>
                                    <td class="text-end">
                                        {% if product_attr.is_blocked %}
                                        <a href="{% url 'cust_admin:catalogue_unlist' pk=product_attr.pk %}" class="btn btn-md rounded font-sm text-end">Unblock</a>&nbsp;&nbsp;
                                        {% else %}
                                        <a href="{% url 'cust_admin:catalogue_unlist' pk=product_attr.pk %}" class="btn btn-md rounded font-sm">Block</a>&nbsp;&nbsp;
                                        {% endif %}
                                        <a href="{% url 'cust_admin:prod_variant_edit' pk=product_attr.pk %}" class="btn btn-light rounded btn-sm font-sm" role="button">Edit </a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                                            </div> <!-- table-responsive //end -->
                </div> <!-- card-body end// -->
            </div> <!-- card end// -->
            <div class="pagination-area mt-30 mb-50">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-start">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                    <i class="material-icons md-chevron_left"></i>
                                </a>
                            </li>
                        {% endif %}
                        {% for num in paginator.page_range %}
                            {% if page_obj.number == num %}
                                <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                    <i class="material-icons md-chevron_right"></i>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </section> <!-- content-main end// -->
        
{% endblock content %}

templates/cust_admin/product/product_list.html
{% extends 'cust_admin/base.html' %}
{% load static %}
{% block content %}
    
    
        <section class="content-main">
            <div class="content-header">
                <div>
                    <h2 class="content-title card-title">{{ title }}</h2>
                    <p></p>
                </div>
                <div>
                    <a href="{% url 'cust_admin:add_product' %}" class="btn btn-md rounded font-sm">Add New Product</a>
                </div>
            </div>
            <div class="card mb-4">
                <header class="card-header">
                    <div class="row gx-3">
                        <div class="col-lg-4 col-md-6 me-auto">
                            <input type="text" placeholder="Search..." class="form-control">
                        </div>
                        <div class="col-lg-2 col-6 col-md-3">
                            <select class="form-select">
                                <option>Status</option>
                                <option>Active</option>
                                <option>Blockd</option>
                                <option>Show all</option>
                            </select>
                        </div>
                        <div class="col-lg-2 col-6 col-md-3">
                            <select class="form-select">
                                <option>Show 20</option>
                                <option>Show 30</option>
                                <option>Show 40</option>
                            </select>
                        </div>
                    </div>
                </header> <!-- card-header end// -->
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th scope="col">id</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Image</th>
                                    <th scope="col">Category</th>
                                    {% comment %} <th scope="col">Sub Category</th> {% endcomment %}
                                    <th scope="col">Is Available</th>
                                    <th scope="col" class="text-end">Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                {% for product in products %}
                                    <tr>
                                        <td>{{ product.p_id }}</td>
                                        <td><b>{{ product.title }}</b></td>
                                        <td>
                                            {% if product.image %}
                                            <img src="{{ product.image.url }}" alt="{{ product.name }}" class="img-sm img-thumbnail" alt="">
                                            {% else %}
                                            <p>No image available</p>
                                            {% endif %}
                                        
                                        </td>
                                        <td>{{ product.category }}</td>
                                        {% comment %} <td>{{ product.sub_category.sub_name }}</td> {% endcomment %}
                                        <td>{{ product.availability }}</td>
                                        <td class="text-end">
                                            {% if product.is_blocked %}
                                                <a href="{% url 'cust_admin:product_unlist' product.p_id %}" class="btn btn-md rounded font-sm text-end">Unblocked</a>&nbsp;&nbsp;
                                            {% else %}
                                                <a href="{% url 'cust_admin:product_unlist' product.p_id %}" class="btn btn-md rounded font-sm">Block</a>&nbsp;&nbsp;
                                            {% endif %}
                                            <a href="{% url 'cust_admin:edit_product' product.p_id %}" class="btn btn-light rounded btn-sm font-sm" role="button">Edit </a>

                                        </td>
                                    
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div> <!-- table-responsive //end -->
                </div> <!-- card-body end// -->
            </div> <!-- card end// -->
            <div class="pagination-area mt-30 mb-50">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-start">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                    <i class="material-icons md-chevron_left"></i>
                                </a>
                            </li>
                        {% endif %}
                        {% for num in paginator.page_range %}
                            {% if page_obj.number == num %}
                                <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                    <i class="material-icons md-chevron_right"></i>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </section> <!-- content-main end// -->
        
{% endblock content %}